### ISSUE TITLE
Product catalog: Ordered list in the sub category description displays incorrect order.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Coastal-Flooring#67]
![image](https://cloud.githubusercontent.com/assets/11186313/13519280/192961cc-e211-11e5-8c35-122a6ee35205.png)

**Comment by ganesh-titan** [comment]
FYI : Please recheck once Ordered list items in sub category description.

![67issue](https://cloud.githubusercontent.com/assets/13450883/13603166/45809f9e-e561-11e5-9fd8-0e4706ea1ceb.png)

**Comment by roseliesromeo** [comment]
Issue happens for newly created category. Once you edit the description, it will work fine.
![image](https://cloud.githubusercontent.com/assets/11186313/13662219/efd715a4-e6d3-11e5-9a0a-1c5bd674354b.png)
